### ISSUE TITLE
Требования к коммитам.

### ISSUE THREAD

**Issue by DariaKrup** [WiillyWonka/RecipesFinder#12]
Прописать в каком-либо из Readme.md ,более жесткие правила к коммитам, при этом добавить примеры.

**Comment by mashaverdina** [comment]
Добавьте, пожалуйста, в конце пример (оформить с помощью маркдаун). И нужно в правила добавить, что нужно указывать номер задачи, чтобы она привязывалась.

**Comment by mashaverdina** [comment]
оформить примеры с помощью маркдаун (markdown)

**Comment by mashaverdina** [comment]
Кстати, вы уверены, что номер спринта не перегружает комментарий и не отъедает слишком много символов. Я не уверена и что вам слово issue нужно. Я не настаиваю, но советую подумать.
