### ISSUE TITLE
Описание продукта.

### ISSUE THREAD

**Issue by DariaKrup** [WiillyWonka/RecipesFinder#2]
Продублировать на английском также, добавить сравнение с аналогами.

**Comment by mashaverdina** [comment]
> Perfect Android app for people who usually have problems with choice what they are going to cook. 

"With choice what" - грамматически неверно. with the choice of what или with choosing 

> Everything is simple - you just need to mention goods you have in your fridge from list and them decide on appropriate recipe. 
 
"from list" - не очень поняла? разве что раньше вместо mention было choose. Но с mention не сочетается.  "theM" - видимо, должно быть "theN". "Need" сюда не очень подходит, лучше, наверное, should. Я бы вообще написала попроще и в повелительно наклонении. Раз уж "Everything is simple".

> Special icons make choice easier - it will be clear which dishes are suitable for vegetarians, which for people keen on spicy ingredients, etc. 

which ARE for people...

> Also some recipes will be support with video or photos to simplify process of cooking.

will be supportED. А вообще как-то канцеляритно немного выходит. Может что-то попроще? recipes support video? contain video? "to simplify process of cooking" - по-моему, the process, но не уверена.

**Comment by mashaverdina** [comment]
"Need" сюда не очень подходит, лучше, наверное, should. Я бы вообще написала попроще и в повелительно наклонении. Раз уж "Everything is simple".
