### ISSUE TITLE
Нарисовать логотип.

### ISSUE THREAD

**Issue by DariaKrup** [WiillyWonka/RecipesFinder#20]
Возможно, стоит в приложении(визуал на гугл диске) на главную страницу поставить фон, на котором будет присутствовать  логотип.

**Comment by DariaZubkova** [comment]
Итоговый вариант логотипа!![IMG_20200313_134614.jpg](https://images.zenhubusercontent.com/5e4a2a318f780f1bf9f8ead2/5e1b695b-e0f5-410c-975f-f6f8c69a1551)
