### ISSUE TITLE
Расписать архитектуру проекта.

### ISSUE THREAD

**Issue by DariaKrup** [WiillyWonka/RecipesFinder#4]
- Примерное описание структуры проекта.

- Возможно, стоит добавить схему или что-то, что наглядно будет демонстрировать этапы разработки.

**Comment by AleksandraBogdan** [comment]
разбить на задачи: бд(схема), сервер(вроде это и есть парсинг), клиент(#7), связь клиента с сервером??, связь сервера с бд??

Расписывать подробно не надо, у вас после каждого спринта может что-то поменять. Не забывайте, что это Agile. Важнее реализация.

**Comment by WiillyWonka** [comment]
Архитектура проекта:

1. БД (Выбран SQLite)
    а) Продумать структуру БД
    б) Реализовать архитектуру
    в) Перевести информацию из json в db

2. Интерфейс пользователя
    а) Продумать детали и дизайн
    б) Реализовать

3. Backend
    а) Продумать внутреннюю логику приложения
    б) Реализовать
4. Протестировать приложение
