### ISSUE TITLE
Подобрать цветовую гамму приложения.

### ISSUE THREAD

**Issue by DariaKrup** [WiillyWonka/RecipesFinder#43]
Под цвета логотипа - что-то с оранжевым.

**Comment by YudzhinNSK** [comment]
![Android Emulator - Pixel_2_API_26_5554 3_29_2020 10_43_17 PM](https://user-images.githubusercontent.com/49250312/77858840-b4675180-720e-11ea-93fb-f6a8a0dd29ca.png)
