### ISSUE TITLE
Найти источник рецептов.

### ISSUE THREAD

**Issue by DariaKrup** [WiillyWonka/RecipesFinder#6]
Если сборник или сайт из интернета из общего доступа, проверяйте лицензию!
Не должно быть запрета на копирование и распространение.

Так же лучше сразу думать о способе, которым будет парситься источник(парсинг в БД).

**Comment by DariaZubkova** [comment]
В итоге выбрали такой сайт для базы рецептов: https://finecooking.ru/category
В приложении нужно будет указать ссылку на них
