### ISSUE TITLE
Макет интерфейса.

### ISSUE THREAD

**Issue by DariaKrup** [WiillyWonka/RecipesFinder#7]
С помощью разных приложений нарисовать макет интерфейса.
Описать окна, которые будут в приложении (как будут выглядеть и как связаны).

и т.д.

**Comment by AleksandraBogdan** [comment]
Опишите окна, которые будут у вас в приложении, как они связаны, сколько их
потом для каждого окна свои задачи будут. И если вы решили на андроиде, то вместо рисовки макета где-то, вы можете это делать сразу в приложении. Все вопросы из описания относятся к каждому окну отдельно.

**Comment by YudzhinNSK** [comment]
https://drive.google.com/open?id=1A3gCT_UlXosFcKbl9VFO3xbuppUJwRCl
