### ISSUE TITLE
Создать пробную версию приложения(release!).

### ISSUE THREAD

**Issue by DariaKrup** [WiillyWonka/RecipesFinder#8]
К концу майлстоуна должна быть версия приложения, которая просто будет запускаться, писать что-либо и успешно закрываться.

**Comment by WiillyWonka** [comment]
![8BR_D1mTQ6w.jpg](https://images.zenhubusercontent.com/5e497bf06a062eb7d2387d21/83f3af33-f5d0-4fc5-9fd7-55e0e06c9bee)
